
# Note that some of the fields in this template haven't been filled in yet.
# Please resolve any `null` fields before launching!

# Whether to run the various GLUE jobs serially or in parallel (use parallel=True to take advantage of multiple GPUs)
parallel: false

# Basic run configuration, additional details will be added to this name for each GLUE task, and each random seed
base_run_name: vanilla-transformer-testing
default_seed: 19
precision: fp32 
max_seq_len: 512 #512, 128

# Tokenizer for dataset creation
tokenizer_name: roberta-base #roberta-base #bert-base-uncased


# Dataloaders (make sure to update these after you modify the starter script!)
train_loader:
  split: train
  tokenizer_name: ${tokenizer_name}
  max_seq_len: ${max_seq_len}
  shuffle: true
  drop_last: true
  num_workers: 8

split_for_testing: test
eval_loader:
  split: ${split_for_testing}
  tokenizer_name: ${tokenizer_name}
  max_seq_len: ${max_seq_len}
  shuffle: true
  drop_last: true
  num_workers: 8

# Optimization
scheduler_name: linear_decay_with_warmup
t_warmup: 0.1dur
alpha_f: 0.02
scheduler:
  name: ${scheduler_name}
  t_warmup: ${t_warmup} #0.06dur #1ep # Warmup to the full LR for 6% of the training duration
  alpha_f: ${alpha_f} # Linearly decay to 0.02x the full LR by the end of the training duration

learning_rate: 2.0e-5
optimizer:
  name: decoupled_adamw
  lr: ${learning_rate}
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-6

# Training duration and evaluation frequency
max_duration: 30ep
eval_interval: 1ep
global_train_batch_size: 16

# Callbacks
callbacks:
  lr_monitor: {}
  speed_monitor: {}

# System
seed: 17
device_eval_batch_size: 16
device_train_microbatch_size: 16

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 50ba

#task_name: 'mimic'
task_name: ecthr
#task_name: 'contract_nli'
#task_name: '20news'
#task_name: hyperpartisan
num_labels: 10
problem_type: multi_label_classification #single_label_classification multi_label_classification
save_folder: ./local-finetune-checkpoints/${tokenizer_name}/${max_seq_len}/${task_name}/${max_duration}/${learning_rate}/${t_warmup}

# (Optional) W&B logging
loggers:
  wandb: 
    project: attention
    entity: hazy-research
    name: ${tokenizer_name}-${max_seq_len}-${split_for_testing}-${max_duration}-${learning_rate}_LR-${scheduler_name}-${t_warmup}-${alpha_f}-${task_name}-${problem_type}

##########################################################

# Base model config
model:
  name: hf_bert
  num_labels: ${num_labels} # <-- Make sure to update these after you modify the starter script!
  use_pretrained: true
  pretrained_model_name: ${tokenizer_name}
  tokenizer_name: ${tokenizer_name}
  problem_type: ${problem_type} #${problem_type}
  save_folder: ${save_folder}
  save_num_checkpoints_to_keep: 10
  model_config:
    num_labels: ${num_labels} # <-- Make sure to update these after you modify the starter script!
    problem_type: ${problem_type}

