
# Note that some of the fields in this template haven't been filled in yet.
# Please resolve any `null` fields before launching!

# Whether to run the various GLUE jobs serially or in parallel (use parallel=True to take advantage of multiple GPUs)
parallel: false

# Basic run configuration, additional details will be added to this name for each GLUE task, and each random seed
base_run_name: monarch-mixer-finetune-glue-960dim-parameter-matched
default_seed: 19
precision: fp32 
max_seq_len: 512 #128

# Tokenizer for dataset creation
tokenizer_name: bert-base-uncased


# Dataloaders (make sure to update these after you modify the starter script!)
train_loader:
  split: train
  tokenizer_name: ${tokenizer_name}
  max_seq_len: ${max_seq_len}
  shuffle: true
  drop_last: true
  num_workers: 8

eval_loader:
  split: validation
  tokenizer_name: ${tokenizer_name}
  max_seq_len: ${max_seq_len}
  shuffle: true
  drop_last: true
  num_workers: 8

# Optimization
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.06dur # Warmup to the full LR for 6% of the training duration
  alpha_f: 0.02 # Linearly decay to 0.02x the full LR by the end of the training duration

optimizer:
  name: decoupled_adamw
  lr: 1.0e-5
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-6

# Training duration and evaluation frequency
max_duration: 3ep
eval_interval: 1ep
global_train_batch_size: 16

# (Optional) W&B logging
loggers:
  wandb: 
    project: attention
    entity: hazy-research

# Callbacks
callbacks:
  lr_monitor: {}
  speed_monitor: {}

# System
seed: 17
device_eval_batch_size: 16
device_train_microbatch_size: 16

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 50ba

#task_name: 'mimic'
#task_name: ecthr
task_name: 'contract_nli'
num_labels: 3
problem_type: multi_label_classification #multi_label_classification

##########################################################

# Loading
starting_checkpoint_load_path: ./local-bert-checkpoints/M2-110M/model.pt
#starting_checkpoint_load_path: ./local-bert-checkpoints/M2-110M/model.pt
#starting_checkpoint_load_path: ./local-bert-checkpoints/M2-260M/model.pt
#starting_checkpoint_load_path: ./local-bert-checkpoints/M2-341M/model.pt
local_pretrain_checkpoint_folder: ./local-bert-checkpoints/

# When starting from mnli
# local_pretrain_checkpoint_folder: ./local-finetune-checkpoints/{base_run_name}/task=mnli/seed=19/
# starting_checkpoint_load_path: ${local_pretrain_checkpoint_folder}/ep3-ba24546-rank0.pt

# Saving
save_finetune_checkpoint_prefix: ./local-finetune-checkpoints/M2-110M/ # (local)
# save_finetune_checkpoint_prefix: s3://<bucket>/remote-finetune-checkpoints # (remote)
save_finetune_checkpoint_folder: ${save_finetune_checkpoint_prefix}/${base_run_name}

#################################################

# Base model config
model:
  #name: bert
  name: mosaic_bert
  pretrained_model_name: ${tokenizer_name}
  tokenizer_name: ${tokenizer_name}
  pretrained_checkpoint: ${starting_checkpoint_load_path}








  use_learnable_monarch: True
  model_config:
    use_learnable_monarch: True







    problem_type: ${problem_type}
    num_labels: ${num_labels}
    num_attention_heads: 12 
    num_hidden_layers: 12 
    attention_probs_dropout_prob: 0.0 
    max_position_embeddings: 128

    #hidden_size: 768
    #intermediate_size: 3072
    hidden_size: 960
    intermediate_size: 3840
    #hidden_size: 1536
    #intermediate_size: 6144
    #hidden_size: 1792
    #intermediate_size: 7168

    monarch_mixer_sequence_mixing: True
    long_conv_l_max: 128
    long_conv_kernel_learning_rate: 1e-3
    hyena_lr_pos_emb: 1e-5
    hyena_w: 10
    hyena_wd: 0.1
    hyena_emb_dim: 5
    hyena_filter_order: 128

    bidirectional: true
    residual_long_conv: true

    use_glu_mlp: True
    use_monarch_mlp: True
    monarch_mlp_nblocks: 4
    use_positional_encodings: True
